---
- src: geerlingguy.apache
- src: geerlingguy.mysql
- src: geerlingguy.postgresql
#- src: dj-wasabi.zabbix-server
- name: dj-wasabi.zabbix-server
  src: https://github.com/dj-wasabi/ansible-zabbix-server.git
  scm: git
